mex nmssPSConnect.cpp .\E710_GCS_DLL\E7XX_GCS_DLL.lib
mex nmssPSDisconnect.cpp .\E710_GCS_DLL\E7XX_GCS_DLL.lib
mex nmssPSGetPosX.cpp .\E710_GCS_DLL\E7XX_GCS_DLL.lib
mex nmssPSGetPosY.cpp .\E710_GCS_DLL\E7XX_GCS_DLL.lib
mex nmssPSSetPosX.cpp .\E710_GCS_DLL\E7XX_GCS_DLL.lib
mex nmssPSSetPosY.cpp .\E710_GCS_DLL\E7XX_GCS_DLL.lib
mex nmssPSXAxisHighEnd.cpp .\E710_GCS_DLL\E7XX_GCS_DLL.lib
mex nmssPSXAxisLowEnd.cpp .\E710_GCS_DLL\E7XX_GCS_DLL.lib
mex nmssPSYAxisHighEnd.cpp .\E710_GCS_DLL\E7XX_GCS_DLL.lib
mex nmssPSYAxisLowEnd.cpp .\E710_GCS_DLL\E7XX_GCS_DLL.lib
